Naive approach only generates json using already exisiting S3 class
knowit/Dataplattform pull request #129
Opened 2020-10-12 19:03 UTC by HeleneSemmerud

2020-10-12 19:05 UTC, HeleneSemmerud commented on packages/common/dataplattform/common/rawStorage.py
> +    return s3.put(data)
@jkrmc12 
Vi vil jo ha noe mer generell data her en .json. 
Et alternativ er vel å utvide S3 klassen med flere metoder, put_raw, put_file etc. Men jeg er litt usikker på om det er et godt design.

2020-10-16 09:17 UTC, jkrmc12 requested changes

2020-10-16 09:17 UTC, jkrmc12 commented on packages/common/requirements.txt
> +Pillow
Hvorfor trenger vi pillow for common-pakken?

2020-10-16 09:17 UTC, jkrmc12 commented on packages/common/tests/test_aws.py
> +    from PIL import Image
Pillow er en ganske stor pakke å dra inn bare for én test. Foreslår at vi skriver om dette til noe litt enklere. Den byte blob-en trenger jo ikke være noe mer komplisert enn en tekstfil

2020-10-16 09:17 UTC, jkrmc12 commented on packages/common/tests/test_aws.py
> +    from PIL import Image
Spesielt mtp at du uansett enkoder/dekoder bildet som en utf-8 tekst string senere i testen uansett

2020-10-16 10:20 UTC, jkrmc12 approved these changes

2020-10-16 10:28 UTC, merged