Implements asynchronic ingestion of documents and images from http re…
knowit/Dataplattform pull request #142
Opened 2020-11-01 21:43 UTC by HeleneSemmerud

…quest to specified buckets

2020-11-01 21:45 UTC, HeleneSemmerud commented on packages/common/tests/test_raw_storage.py
> +    environ['ACCESS_PATH'] = ''
unødvendig, ta vekk

2020-11-01 21:51 UTC, HeleneSemmerud commented on services/utils/downloadToPublicBucket/test_data.json
> +    "path": "public"
ta vekk

2020-11-01 21:51 UTC, HeleneSemmerud commented on templates/downloadToPrivateBucket/test_data.json
> +    "path": "private"
ta vekk

2020-11-01 21:52 UTC, HeleneSemmerud commented on templates/downloadToPrivateBucket/test_downloadToPrivateBucket.py
> +class FakeResponse:
Bruk klasse definert i plugin

2020-11-02 08:21 UTC, HeleneSemmerud commented on packages/common/dataplattform/common/aws.py
> +        self.access_path = environ.get("ACCESS_PATH") if access_path is None else access_path
Dette er innført fordi det ikke gikk ann å legge noe til på root-pathen til en bøtte. 
`access_path or environ.get("ACCESS_PATH")` gir alltid `environ.get("ACCESS_PATH") selvom input `access_path` er definert som tom streng.

2020-11-02 10:29 UTC, jkrmc12 requested changes

2020-11-02 10:29 UTC, jkrmc12 commented on packages/common/dataplattform/common/helper.py
> +class Helper():
Statiske klasser er helt unødvendig i `python`. Alle disse funksjonene kan ligge i modul-scope

2020-11-02 10:29 UTC, jkrmc12 commented on packages/common/dataplattform/common/helper.py
> +    def download_from_http(self, body: dict = {}):
`body` er litt misvisende ettersom det ser ut som dette egentlig refererer til et http-request. Det er også rart at argumentet er optional med default som en tom dict da jeg ikke tror funksjonen fungerer uten noen av parameterene

2020-11-02 10:29 UTC, jkrmc12 commented on packages/common/dataplattform/common/raw_storage.py
> +        self.access_path = ''
Ser ikke ut som `access_path` noen gang blir satt til noe annet enn default, så kan slettes (da trenger ikke dette være en klasse heller)

2020-11-02 10:29 UTC, jkrmc12 commented on packages/testing/dataplattform/testing/plugin.py
> +class FakeResponse:
Så lenge den ikke er relatert til noe `pytest` skal loade, fixtures, hooks, etc.. så trenger det ikke være i denne filen

2020-11-02 10:29 UTC, jkrmc12 commented on services/ingestion/cvPartner/cv_partner_ingest_lambda.py
> +    def write_cv_doc_to_private_bucket(person, language: str = 'no', ext: str = 'pdf'):
Hvorfor kan vi ikke abstrahere bort "last ned og lagre"- logikken til dette nivået? Jeg synes ikke man skal trenge å forholde seg til hvordan dataen blir lagret (om det skjer async eller ikke) på dette nivået

2020-11-02 10:29 UTC, jkrmc12 commented on services/ingestion/cvPartner/cv_partner_ingest_lambda.py
> +    def write_cv_doc_to_private_bucket(person, language: str = 'no', ext: str = 'pdf'):
(ish dette nivået i hvert fall)

2020-11-02 10:29 UTC, jkrmc12 commented on services/utils/downloadToPublicBucket/serverless.yml
> +service: downloadToPublicBucket
Å ha en lambda for public/private-access trenger ikke være splittet opp i to tjenester/serverless-filer. Du kan ha flere lambdaer i én og samme serverless-fil med hver sin access-rolle. Hver lambda i en serverless-fil kan også bruke samme handler-funksjon/fil for gjenbruk av den samme koden, bare med forskjellig rolle.

Enda bedre hadde vært hvis den påtok seg riktig rolle basert på eventet, så slipper vi ekstra infrastuktur-kompleksitet

2020-11-04 13:40 UTC, jkrmc12 requested changes

2020-11-04 13:40 UTC, jkrmc12 commented on services/utils/downloadToBucket/downloadToBucket.py
> +from dataplattform.common.helper import download_from_http
Vi bruker snake_case som filnavn på python-filer

2020-11-04 13:40 UTC, jkrmc12 commented on services/utils/downloadToBucket/package.json
> +  "name": "DOWNLOAD_TO_PRIVATE_BUCKET",
Bør være samme som service-navnet i serverless filen, så er det likt overalt

2020-11-04 13:40 UTC, jkrmc12 commented on services/utils/downloadToBucket/downloadToBucket.py
> +        'statusCode': download_from_http(event.get('body'))
Blir koden i `download_from_http` brukt noe annet sted enn herfra? Et den ligger et annet sted men kun brukes her øker kompleksitet unødvendig

2020-11-04 13:40 UTC, jkrmc12 commented on packages/common/dataplattform/common/helper.py
> +    return response.status
```suggestion
def download_from_http(http_request, filename, filetype, private=True):
    url = http_request.get('url')
    if not url:
       raise some_error
       
    headers = http_request.get('header', {})

    valid_content_types = {'pdf':  'application/pdf',
                           'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                           'jpg':  'image/jpeg'}

    if filetype not in list(valid_content_types.keys()):
        return 400

    req = request.Request(url)
    for (header, value) in headers.items():
        req.add_header(header, value)

    bucket = environ.get('PRIVATE_BUCKET') if private else environ.get('PUBLIC_BUCKET')

    response = request.urlopen(req)
    content_type = response.getheader('Content-Type')
    if content_type == valid_content_types[filetype]:
        if (response.status == 200 and response.readable()):
            write_file_to_bucket(data=response.read(),
                                 filename=filename,
                                 bucket=bucket)
        else:
            return 400
    else:
        return 400
    return response.status
```

Jeg så etter å ha skrevet litt at dette _egentlig_ er handler funksjonen til downloader lambdaen. Det jeg egentlig ser etter er en tydeligere signatur for `save_document` så ikke faktisk non-optional argumenter er gjort optional i at alt sammen er bakt inn i en dictionary

2020-11-04 17:28 UTC, HeleneSemmerud commented on services/utils/downloadToBucket/downloadToBucket.py
> +from dataplattform.common.helper import download_from_http
Hva mener du her?

2020-11-04 17:30 UTC, HeleneSemmerud commented on services/utils/downloadToBucket/package.json
> +  "name": "DOWNLOAD_TO_PRIVATE_BUCKET",
Dette er en glipp

2020-11-04 17:38 UTC, HeleneSemmerud commented on services/utils/downloadToBucket/downloadToBucket.py
> +from dataplattform.common.helper import download_from_http
Det er helper.py som er filnavnet, download_from_http er en metode. Ser ut som jeg følger samme struktur som i resten av common-mappen.

2020-11-04 17:57 UTC, jkrmc12 commented on services/utils/downloadToBucket/downloadToBucket.py
> +from dataplattform.common.helper import download_from_http
Jeg siktet til filen `downloadToBucket.py` (ingen måte å kommentere en fil med github, bare linjer)

2020-11-04 19:03 UTC, HeleneSemmerud commented on packages/common/dataplattform/common/helper.py
> +    return response.status
Jeg er enig med det at alt dette egentlig bare kan legges rett inn i download-lambdaen, så det innfører jeg nå. Jeg gjør det slik at eventet ser slik ut: 
```
{
    "body": {
        "requestUrl": "<url>",
       "header: {},
    },
    "filename": "<filename>",
    "filetype": "<filetype>",
    "private": false
}```  
Så separeres optional og non-optional parametere. 

Når det gjelder parameter validering og generell input-sjekking, er da forslaget ditt at vi endrer fra å returnere 400, Bad request, til å kaste en exception, slik du har nevnt på linje 18 i forslaget ditt? 

Takk for nyttige kommentarer.

2020-11-05 09:16 UTC, jkrmc12 approved these changes

2020-11-05 10:32 UTC, merged