Feature/cache update on data update
knowit/Dataplattform pull request #153
Opened 2020-11-27 15:15 UTC by alfredronning

closes knowit/Dataplattform-issues#286

- La til støtte for oppdatering av cache
- La til melding på DataUpdate topic når data oppdateres
- Skrev tester for cache_updater, reportsrepository + ny kode

2020-11-30 08:51 UTC, HeleneSemmerud commented on packages/common/dataplattform/common/handlers/process.py
> +        updated_lists = []
kan ta bort deklarering av denne her og på linjen under

2020-11-30 09:01 UTC, HeleneSemmerud commented on services/api/dataApi/requirements-test.txt
> +fastparquet
dere trenger ikke denne importen her

2020-11-30 09:04 UTC, HeleneSemmerud commented on packages/common/dataplattform/common/handlers/process.py
> +        updated_lists = []
denne er overflødig?

2020-11-30 09:07 UTC, HeleneSemmerud commented on services/api/dataApi/common_lib/common/tests/test_reports.py
> +from common.repositories.reports import ReportsRepository
Isteden for å bruker ReportsRepository as repo over alt så går det an å ta 
`import common.repositories.reports.Repository as repo` her oppe tror jeg?

2020-11-30 14:44 UTC, choffa commented on services/api/dataApi/common_lib/common/tests/test_reports.py
> +from common.repositories.reports import ReportsRepository
Nei fordi `as` gjør to forskjellige ting her. Etter `import` betyr det alias, mens etter `with` betyr det variabelnavn.

2020-11-30 14:55 UTC, choffa commented on services/api/dataApi/requirements-test.txt
> +fastparquet
Testene brekker på Github vis vi ikke har den 🤷

2020-11-30 15:00 UTC, choffa commented on packages/common/dataplattform/common/handlers/process.py
> +        updated_lists = []
Ja, der har jeg bare ikke fulgt helt med i svingene 😅

2020-12-03 10:32 UTC, HeleneSemmerud commented on services/api/dataApi/common_lib/common/repositories/reports.py
> +                print(e.response['Error']['Message'])
kan ta vekk denne

2020-12-03 15:01 UTC, HeleneSemmerud approved these changes

2020-12-07 08:44 UTC, HeleneSemmerud requested changes
Legg til sns permissions i alle serverless.yml filene for alle servicene, slik dere gjorde for test_lambdaen

2020-12-08 21:09 UTC, HeleneSemmerud commented on services/infrastructure/events/serverless.yml
> +      Type: AWS::IAM::ManagedPolicy
Oi, dette var nytt for meg :) Hvorfor skal det være en managedPolicy?

2020-12-11 08:06 UTC, choffa commented on services/infrastructure/events/serverless.yml
> +      Type: AWS::IAM::ManagedPolicy
Jeg prøvde først med `AWS::IAM::Policy` men den krever at du setter én av `Users`, `Groups`, eller `Roles` ved opprettelse. Dvs. at man må tilordne polisen ved opprettelse. Siden denne polisen skal være akkurat lik for alle, ville jeg bruke `!ImportValue`, som jeg tror vi også snakka kort om. Ved å bruke `AWS::IAM:ManagedPolicy` kan man opprette polisen og tilordne den ressurser senere.

Alternativet hadde kanskje vært å gjøre motsatt, dvs eksportere rollen eller gruppen fra ingestion servicen sin `serverless.yml` og importere denne her. Ulempen er at man da må endre og deployere to plasser for en ny service.

2020-12-16 08:11 UTC, HeleneSemmerud approved these changes

2020-12-16 08:12 UTC, merged