Feature/update crawler on new table
knowit/Dataplattform pull request #160
Opened 2021-01-14 10:21 UTC by alfredronning

Kanskje en litt overkomplisert løsning for å sikre potensielle race conditions.

Problemet med å oppdatere krawleren, er at den ikke kan oppdateres men den kjører.
Hvis to events samtidig sjekker om den kjører, begge ser at den er "READY", og begge oppdaterer og kjører samtidig, kan dette bli krøll.

Når nye tabeller blir oprettet, blir en melding sendt til en SQS kø.
En lambda tar imot meldinger fra denne køen i serie, stopper crawleren hvis den kjører, venter til den er klar, og oppdaterer og kjører.

2021-01-15 12:48 UTC, choffa reviewed
Jeg har lagt inn noen kommentarer som er relatert spesifikt til denne koden. Men når det er sagt er det kanskje en større diskusjon som er verdt å ta her.

Jeg lurer fortsatt på hvor viktig det er at crawleren blir _startet_ automatisk? Den kjører jo en gang i døgnet, og kan eventuelt startes manuelt i konsollen, eller Dataplattform CLI. Så kanskje det viktigste er at tabellen blir lagt til i Crawleren sin liste av kilder, så får vi #eventual consistency" uansett.
**Fordel**: Mye mindre komplisert. Kan gjøres direkte uten egen kø og ekstra lambda
**Ulempe**: Nye tabeller blir ikke automatisk tilgjengelig for spørring _umiddelbart_ men krever at man venter eller gjør noe manuelt.

Så vurderingen blir da om den økte kompleksiteten er verdt fordelen med _umiddelbar_ automatikk. Hva tenker dere @HeleneSemmerud og @alfredronning? 😄

2021-01-15 12:48 UTC, choffa commented on packages/common/dataplattform/common/aws.py
> +        except ClientError as e:
Tror denne er unødvendig. Dersom du ikke faktisk håndterer feilen, så fører den til et krasj uansett men med en annen feil som påstått årsak. Men `ClientError` kan inneholde mer info, som kanskje ikke kommer med i en vanlig print, som kan være interresant å hente og printe

2021-01-15 12:48 UTC, choffa commented on packages/common/dataplattform/common/aws.py
> +        response = self.client.get_queue_url(QueueName=queue_name or environ.get("SQS_QUEUE_NAME"))
Ville ha fjerna `environ::get` kallet her, siden den variabelen brukes til noe helt annet. Evt. bytte til `SQS_CRAWLER_QUEUE_NAME`

2021-01-15 12:48 UTC, choffa commented on packages/common/dataplattform/common/aws.py
> +                'message': {
Tror ikke det er nødvendig å ha med hele `message` i attributter her. Ser at det er omtrent det som er gjort tidligere, men det blir som å sende noe i både `header` og `body` på et nettverkskall. Attributter er ment som metadata for meldingen, og kan f. eks. ikke krypteres, slik `MessageBody` kan

2021-01-15 12:48 UTC, choffa commented on services/ingestion/gitHub/serverless.yml
> +          - PolicyName: ${self:custom.stage}-crawler-${self:service}-${self:custom.editable.ingestHandlerFile}-sqsRole
Siden alle skal gjøre det samme på den samme ressursen, tror jeg det er bedre å bruke en `AWS::IAM::ManagedPolicy` heller enn én identisk policy hver

2021-01-15 13:37 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +        response = self.client.get_queue_url(QueueName=queue_name or environ.get("SQS_QUEUE_NAME"))
hmm ja, her skulle det stått SQS_CRAWLER_QUEUE_NAME. Den brukes kun hvis argumentet queue_name er None, noen som det aldri er, så fikk aldri noen feil på den.
Har bare glemt å endre der / ta den bort.

Godt sett!

2021-01-15 14:01 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +        except ClientError as e:
Ja den kanskje ikke nødvendig nei. Så det ble gjort på denne måten i dataplattorm cli, men det er jo funksjoner som er brukes mer til testing og debugging.

2021-01-15 14:02 UTC, alfredronning commented on services/ingestion/gitHub/serverless.yml
> +          - PolicyName: ${self:custom.stage}-crawler-${self:service}-${self:custom.editable.ingestHandlerFile}-sqsRole
Ja sant, blir unødvendig duplikat

2021-01-15 14:33 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +                'message': {
Ja tror ikke jeg har forstått helt hvordan formatet på denne metadataen skal se ut. Men å putte hele messagebody i den er vel kanskje ikke det den er tenkt til nei. Kanskje 'StringValue': "json_string"?

2021-01-15 14:34 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +        except ClientError as e:
Ja den er nok ikke nødvendig nei. Så det ble gjort på denne måten i dataplattorm cli, men det er jo funksjoner som er brukes mer til testing og debugging.

2021-01-15 14:34 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +        response = self.client.get_queue_url(QueueName=queue_name or environ.get("SQS_QUEUE_NAME"))
hmm ja, her skulle det stått SQS_CRAWLER_QUEUE_NAME. Den brukes kun hvis argumentet queue_name er None, noen som det aldri er, så fikk aldri noen feil på den.
Har bare glemt å endre der / ta den bort.

Godt sett!

2021-01-15 14:35 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +                'message': {
Ja tror ikke jeg har forstått helt hvordan denne metadataen skal se ut. Men å putte hele messagebody i den er vel kanskje ikke det den er tenkt til nei. Kanskje 'StringValue': "json_string"?

2021-01-15 14:36 UTC, alfredronning commented on services/ingestion/gitHub/serverless.yml
> +          - PolicyName: ${self:custom.stage}-crawler-${self:service}-${self:custom.editable.ingestHandlerFile}-sqsRole
Ja sant det blir unødvendig duplikat

2021-01-22 09:31 UTC, choffa commented on packages/common/dataplattform/common/aws.py
> +                'message': {
Den er valgfri så vidt jeg vet, så den kan se ut akkurat slik du vil at den skal se ut 😄

2021-01-22 14:02 UTC, HeleneSemmerud requested changes
Se kommentar

2021-01-22 15:07 UTC, choffa commented on packages/common/dataplattform/common/handlers/process.py
> +            update_crawler = not table_exists
Er det mulig å sjekke om tabellen eksisterer på Crawleren mens den kjører, og dermed omgå problemet over? Eller er det ikke lov å gjøre noe med crawlere mens de holder på?

2021-01-22 15:35 UTC, alfredronning commented on packages/common/dataplattform/common/aws.py
> +            # Will not update if crawler is running
Nei verken kjøring eller oppdatering funker hvis den kjører. Som nå er 1gang pr dag.

2021-01-22 15:45 UTC, alfredronning commented on packages/common/dataplattform/common/handlers/process.py
> +            update_crawler = not table_exists
Man kan kjøre getCrawler som returner metadata med bl. a s3targets, mens den kjører.
Update crawler variabelen er tenkt for å lagre om tabellen eksisterer eller ikke, etter som crawleren ikke skal oppdateres på overwrite.

Kan du utdype litt mer hva du mener med problemet over?

2021-01-22 15:53 UTC, choffa commented on packages/common/dataplattform/common/handlers/process.py
> +            update_crawler = not table_exists
Problemet over:
> Så dersom Crawleren tilfeldigvis kjører på første ingest, så vil tabellen ikke bli lagt til?

Poenget mitt var at det interessante er jo om tabellen _er lagt til crawleren_, ergo dersom du endrer `update_crawler` variabelen til å representere om tabellen ligger på crawleren, heller enn om den eksisterer fra før. Da vil det være slik at dersom crawleren tilfeldigvis kjørte mens man prøvde å legge til første gang så vil den prøve igjen neste gang fordi den da ikke ble lagt til forrige gang.

Det er klart det er veldig lite sannsynlig at dette skjer, men jeg ser for meg at det kan være en kilde til forvirring dersom det mot formodning skulle skje. Men dersom det er vesentlig vanskeligere så har jeg ikke noe mot å droppe det siden det er så lite sannsynlig 😄

2021-01-22 16:00 UTC, alfredronning commented on packages/common/dataplattform/common/handlers/process.py
> +            update_crawler = not table_exists
Ja det har jeg egentlig ikke tenkt på, da vil en potensiell update under kjøring senere bli lagt til. Skal teste det!

2021-01-25 12:57 UTC, choffa commented on packages/common/dataplattform/common/aws.py
> +        self.access_level = environ.get('ACCESS_LEVEL') if access_level is None else access_level
Her kan du bruke `access_level or environ.get('ACCESS_LEVEL')` ettersom `None` er falsy.

2021-01-25 12:57 UTC, choffa commented on packages/common/dataplattform/common/handlers/process.py
> +                access_path=environ.get('ACCESS_PATH'))
Disse to er vel unødvendige når det uansett er defaulten?

2021-01-25 13:53 UTC, choffa approved these changes

2021-01-27 10:09 UTC, choffa approved these changes

2021-01-27 10:10 UTC, merged