Feature/405 mock ubw customer per resource
knowit/Dataplattform pull request #225
Opened 2021-06-17 12:28 UTC by kristjgr

2021-06-17 14:25 UTC, leevi978 approved these changes

2021-06-17 14:28 UTC, leevi978 requested changes

2021-06-17 14:28 UTC, leevi978 commented on services/ingestion/ubwCustomerPerResource/serverless.yml
>      IngestLambdaRole:
Denne bør vell også være conditional på samme måte som MockLambdaRole?

2021-06-18 06:54 UTC, kristjgr commented on services/ingestion/ubwCustomerPerResource/serverless.yml
>      IngestLambdaRole:
Definitivt! Ble det lagt til nå?

2021-06-18 07:25 UTC, leevi978 approved these changes

2021-06-18 07:25 UTC, leevi978 commented on services/ingestion/ubwCustomerPerResource/serverless.yml
>      IngestLambdaRole:
Det ble det!

2021-06-22 06:54 UTC, merged