Added lint workflow for api and infrastructure
knowit/Dataplattform pull request #244
Opened 2021-07-01 12:59 UTC by kristjgr

2021-07-01 13:13 UTC, leevi978 requested changes

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/api-documentation.yml
> +      - 'packages/api/**'
Har du sjekka om `services/api/documentation` faktisk er avhengig av `packages/api`?

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/api-documentation.yml
> +      - 'packages/api/**'
Har du sjekka om `services/api/documentation` faktisk er avhengig av `packages/api`?

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-distribution.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/distribution
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-events.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/events
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-glue.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/glue
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-ingestApiGateway.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/ingestApiGateway
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-layers.yml
> +          yamllint -c ./.config/.yamllint ./services/infrastructure/layers
Her bør det være en egen workflow per layers stack, og ikke én for alle layers

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-monitoring.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/monitoring
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-storage.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/storage
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-01 13:13 UTC, leevi978 commented on .github/workflows/infrastructure-vpc.yml
> +          flake8 --config=./.config/.flake8 ./services/infrastructure/vpc
Denne mappa har ingen python filer, så linting med flake8 er unødvendig

2021-07-02 07:16 UTC, kristjgr commented on .github/workflows/api-documentation.yml
> +      - 'packages/api/**'
documentation har ikke en requirements.txt fil, så da er den kanskje ikke avhengig av `packages/api` ?

2021-07-02 07:41 UTC, leevi978 commented on .github/workflows/api-documentation.yml
> +      - 'packages/api/**'
Da virker det ikke sånn

2021-07-02 14:00 UTC, leevi978 approved these changes

2021-07-05 10:44 UTC, merged