Feature/439 automatic record cloudfront
knowit/Dataplattform pull request #255
Opened 2021-07-08 10:27 UTC by Flexman94

Stackene Distribution, Documentation og Filestoragedistribution tar hånd om recordene de selv bruker i routes 53.

2021-07-08 12:57 UTC, leevi978 requested changes

2021-07-08 12:57 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Ser at hostedzone er hardkoda her. Her mener jeg at før dette merges bør vi først må få inn PR for en hosted zone stack som eksporterer denne id'en, og deretter oppdatere denne PR'en til å importere den

2021-07-08 12:57 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Eventuelt bruker du samme SSM som du har brukt over, og legger inn et issue om at SSM skal byttes ut med export + import ved et senere tidspunkt

2021-07-08 12:57 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
SSM bør ved et senere tidspunkt byttes til export fra hosted zone stack og import her. Jeg foreslår at vi først får inn PR med stack for hosted zone og oppdaterer dette PR'et til å bruke importvalue. Eller så legger du inn et issue om at dette skal byttes om senere.

2021-07-08 12:57 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
SSM bør ved et senere tidspunkt byttes til export fra hosted zone stack og import her. Jeg foreslår at vi først får inn PR med stack for hosted zone og oppdaterer dette PR'et til å bruke importvalue. Eller så legger du inn et issue om at dette skal byttes om senere.

2021-07-08 12:57 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
SSM bør ved et senere tidspunkt byttes til export fra hosted zone stack og import her. Jeg foreslår at vi først får inn PR med stack for hosted zone og oppdaterer dette PR'et til å bruke importvalue. Eller så legger du inn et issue om at dette skal byttes om senere.

2021-07-08 12:57 UTC, leevi978 commented on services/api/fileStorageDistribution/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
SSM bør ved et senere tidspunkt byttes til export fra hosted zone stack og import her. Jeg foreslår at vi først får inn PR med stack for hosted zone og oppdaterer dette PR'et til å bruke importvalue. Eller så legger du inn et issue om at dette skal byttes om senere.

2021-07-08 12:57 UTC, leevi978 commented on services/api/fileStorageDistribution/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Samme kommentar som for `documentation`

2021-07-08 12:57 UTC, leevi978 commented on services/infrastructure/distribution/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
SSM bør ved et senere tidspunkt byttes til export fra hosted zone stack og import her. Jeg foreslår at vi først får inn PR med stack for hosted zone og oppdaterer dette PR'et til å bruke importvalue. Eller så legger du inn et issue om at dette skal byttes om senere.

2021-07-08 12:57 UTC, leevi978 commented on services/infrastructure/distribution/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Se kommentaren om hardkoda id i `documentation`

2021-07-08 13:51 UTC, Flexman94 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Den id-en der er fast og skal ikke ligge i parameter store.
Den hostedzonen indikerer til aws at den aliasrecorden er en cloudfront distribusjon.

2021-07-08 13:55 UTC, Flexman94 commented on services/api/documentation/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
Det vil komme an på hvordan vi løser problemet med at filestoragedistribution er i feil region.
Om vi flytter den til eu central 1 vil løsningen som du foreslår her og jeg prøvde på før jeg ga opp og stuet det vekk i issue 452 fungere.
Hvis vi ikke flytter den er vi nødt til å bruke andre metoder for å sende den Id-en rundt.

2021-07-08 14:02 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Men hva skjer når man skal deploye til flere miljøer samtidig? Vil denne hardkoda id'en fungere på alle aws kontoer?

2021-07-08 14:23 UTC, Flexman94 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
Ja

2021-07-08 14:28 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +              HostedZoneId: Z2FDTNDATAQYW2
for dokumentasjons skyld: hostedZoneId skal ifølge https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html være satt til Z2FDTNDATAQYW2 dersom den peker på en cloudfront distribusjon

2021-07-13 08:08 UTC, Flexman94 commented on services/api/documentation/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
Jeg tenker at denne kan merges nå da denne fungerer utmerket med det oppsette vi har i new-dev nå.
Har alt opprettet et issue på å fullstendig automatisere hostedzone oppsettet. Men det er mer omfattende og vil ta mer tid, tid hvor vi kunne ha merget denne og hatt nytten av den automatiserte oppdateringen av cloudfront alias urler.

2021-07-13 08:31 UTC, leevi978 commented on services/api/documentation/serverless.yml
> +        HostedZoneId: ${ssm:/${self:custom.stage}/routes/hostedzoneid}
Den er god

2021-07-13 08:31 UTC, leevi978 submitted a review, later dismissed

2021-07-13 09:12 UTC, leevi978 approved these changes

2021-07-13 09:12 UTC, merged