deploy and remove services in parallel
knowit/Dataplattform pull request #265
Opened 2021-07-29 07:46 UTC by kristjgr

2021-07-29 08:15 UTC, leevi978 requested changes

2021-07-29 08:15 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +        os.remove(temp_file_path)
Her bør det kanskje være en try/catch med en forklarende feilmelding hvis noe går galt. Ved å google python exceptions tutorial eller noe lignende så bør du finne informasjon om hvordan det er smart å gjøre det

2021-07-29 08:15 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +        sys.stdout = open(temp_file_path, "a")
Her bør det kanskje være en try/catch med en forklarende feilmelding hvis noe går galt. Ved å google python exceptions tutorial eller noe lignende så bør du finne informasjon om hvordan det er smart å gjøre det

2021-07-29 08:15 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +        traceback.print_stack()
Her printes stacen 2 ganger

2021-07-29 08:32 UTC, kristjgr commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def separate_sequential_services(dependency_graph, has_no_dependencies, iteration):
Fungerer dette? 
# Puts services dependent on 'serverless-python-requirements' plugin in an isolated level so they run in sequential

2021-07-29 08:40 UTC, kristjgr commented on packages/cli/dataplattform/cli/commands/deploy.py
> +    elif args.remove:
Da lurer jeg på hvor den args.config_file kommer inn, er det noe som skal kjøres før hver deploy?

2021-07-29 08:48 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +    elif args.remove:
config kan kjøres som vanlig før hele deploy biten. Det den gjør er å sette en rekke SSM parametere i AWS sånn at man slipper å gå i konsollen og konfigurere én av gangen

2021-07-29 08:49 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def separate_sequential_services(dependency_graph, has_no_dependencies, iteration):
Jepp, perfekt :)

2021-07-29 11:54 UTC, kristjgr commented on packages/cli/dataplattform/cli/commands/deploy.py
> +    elif args.remove:
```
if parallel:
    dependency_graph = create_dependency_graph()
    if remove:
        dependency_graph.reverse()
        undeploy(dependency_graph)
    else:
        if config_file: 
              do something
        deploy(dependency_graph)
else:
    if remove:
        paths.reverse()
        undeploy(paths)
    else:
        if config_file: 
              do something
        deploy(paths)
```

Sånn her?

2021-07-29 12:12 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +    elif args.remove:
Trur heller jeg ville gjort sånn:

````
if config_file != null:
    do_config(config_file)

if parallel:
    dependency_graph = create_dependency_graph()
    if remove:
        dependency_graph.reverse()
        undeploy(dependency_graph)
    else:
        deploy(dependency_graph)
else:
    if remove:
        paths.reverse()
        undeploy(paths)
    else:
        deploy(paths)
````

2021-07-29 12:51 UTC, kristjgr commented on packages/cli/dataplattform/cli/commands/deploy.py
> +    elif args.remove:
åja, okei! Trodde den måtte være i forbindelse med `if deploy`

2021-07-29 14:52 UTC, leevi978 requested changes

2021-07-29 14:52 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +            print_failed_status(paths, "removals")
Er det meningen at `print_failed_status` skal kjøre hver gang? Syntes dette så litt rart ut, siden det ikke er noen sjekk for om det feila eller ikke

2021-07-29 14:52 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +            print_failed_status(paths, "removals")
Sjekka nettopp hva funksjonen gjorde og den har et litt forvirrende navn. Kanskje `print_success_status` er mer forklarende? Hvert fall ville det vært det for min del

2021-07-30 07:42 UTC, kristjgr commented
La også til en seksjon om flagget i dokumentasjonen.

2021-07-30 07:45 UTC, kristjgr commented on packages/cli/dataplattform/cli/commands/deploy.py
> +        update_database()
Databaseoppdatering var vel originalt kun etter depoly, så det skal kanskje ikke oppdateres ved remove?

2021-07-30 10:15 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +        update_database()
Nei, databaser skal ikke oppdateres etter remove. Bra observert

2021-09-01 14:43 UTC, bjorn-iversen commented
Hva skjer dersom service `B` avhenger av service `A`, men service `B` sin deployment blir ferdig før service `A`?

2021-09-01 14:57 UTC, leevi978 commented
> Hva skjer dersom service `B` avhenger av service `A`, men service `B` sin deployment blir ferdig før service `A`?

Slik jeg forstod det skulle dette skriptet deploye puljevis i topologisk rekkefølge slik at en tjeneste ikke deployes før alle tjenestene den er avhengig av er ferdig å deploye.

2021-09-01 15:01 UTC, bjorn-iversen commented
> > Hva skjer dersom service `B` avhenger av service `A`, men service `B` sin deployment blir ferdig før service `A`?
> 
> Slik jeg forstod det skulle dette skriptet deploye puljevis i topologisk rekkefølge slik at en tjeneste ikke deployes før alle tjenestene den er avhengig av er ferdig å deploye.

Hmm, jeg sliter med å se at det er dette som skjer... får se nærmere på koden i morgen.

2021-09-02 07:22 UTC, bjorn-iversen commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def services_without_dependencies(dependency_graph, dependencies, iteration):
Hva er poenget med denne funksjonen? Hvorfor kan ikke tjenester som bruker pluginen `serverless-python-requirements` kjøres i parallell?

2021-09-02 08:06 UTC, bjorn-iversen commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def services_without_dependencies(dependency_graph, dependencies, iteration):
Diskuterte dere dette, @leevi978 ?

2021-09-02 08:12 UTC, bjorn-iversen commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def services_without_dependencies(dependency_graph, dependencies, iteration):
Eventuelt @kristjgr om du leser dette :D

2021-09-02 09:38 UTC, leevi978 commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def services_without_dependencies(dependency_graph, dependencies, iteration):
Nå begynner dette å bli litt lenge siden, men jeg har vage minner om at det oppsto feilmeldinger dersom to forskjellige tjenester prøvde å aksessere samme pip-mappe

2021-09-02 09:40 UTC, bjorn-iversen commented on packages/cli/dataplattform/cli/commands/deploy.py
> +def services_without_dependencies(dependency_graph, dependencies, iteration):
Aha, takk skal du ha!

2021-11-30 11:44 UTC, closed without merging