Feature/458 lage scripts for å slette og opprette rapporter automatisk
knowit/Dataplattform pull request #538
Opened 2023-04-03 10:48 UTC by kjell-r

First draft for report update/maintenance tool

2023-04-11 12:50 UTC, thomasduy commented on packages/cli/dataplattform/cli/commands/reports/update.py
> +    api_stub_report = ".dataplattform.knowit.no/data/report"
Vil alle nå få mulighet til å kunne endre rapporter uavhengig av tilganger?

2023-04-12 08:25 UTC, kjell-r commented on packages/cli/dataplattform/cli/commands/reports/update.py
> +    api_stub_report = ".dataplattform.knowit.no/data/report"
Mulig jeg ikke forstår spørsmålet helt? Det er samme tilganger som når man logger på direkte i openAPI/Swagger APIet. Dvs. foreløpig google auth, senere AD når det er på plass.

2023-04-13 07:42 UTC, thomasduy commented on packages/cli/dataplattform/cli/commands/reports/update.py
> +    api_stub_report = ".dataplattform.knowit.no/data/report"
Spørsmålet er egentlig rundt autentisering. Om alle som har tilgang til CLI-et vil nå kunne gjøre endringer i prod/dev? Siden tokens og sånt er hardkodet, men kan hende det er noe jeg misforstår.

2023-04-13 08:58 UTC, kjell-r commented on packages/cli/dataplattform/cli/commands/reports/update.py
> +    api_stub_report = ".dataplattform.knowit.no/data/report"
KlientIDs til miljøene ligger der, bør de ikke det? Det er bare en peker til hva som tar seg av påloggingen. Selve påloggingen går gjennom en nettside til google som gir tilbake auth token.

2023-04-13 10:55 UTC, thomasduy commented on packages/cli/dataplattform/cli/commands/reports/update.py
> +    api_stub_report = ".dataplattform.knowit.no/data/report"
Ok skjønner, da er jeg nok enig med at de kan ligge der.

2023-04-13 10:56 UTC, thomasduy approved these changes

2023-04-14 07:09 UTC, larsgus commented
> Det må kanskje settes opp noe mer på dependencies for at de skal være tilgjengelige for alle? Jeg er n00b på ting som har med pyproject.toml/setup.cfg/setup.py å gjøre...



> Det må kanskje settes opp noe mer på dependencies for at de skal være tilgjengelige for alle? Jeg er n00b på ting som har med pyproject.toml/setup.cfg/setup.py å gjøre...

Ja, jeg ville nok hatt en requirements.txt fil eller noe lignende setup greier. Særlig om dette skal kjøres i en CI/CD pipeline

2023-04-14 07:10 UTC, larsgus requested changes
> Det må kanskje settes opp noe mer på dependencies for at de skal være tilgjengelige for alle? Jeg er n00b på ting som har med pyproject.toml/setup.cfg/setup.py å gjøre...

Ja, jeg ville nok hatt en requirements.txt fil eller noe lignende setup greier. Særlig om dette skal kjøres i en CI/CD pipeline

2023-05-10 10:18 UTC, merged