Feature/add poller cv partner
knowit/Dataplattform pull request #92
Opened 2020-07-24 07:50 UTC by long11

- Add an ingest_lambda
- Add a process lambda
- Added test

2020-07-24 09:14 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +ath = Athena()
ubrukt variabel

2020-07-24 09:14 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +from dataplattform.query.engine import Athena
ubrukt import

2020-07-24 09:20 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +ath = Athena()
ubrukt variabel

2020-07-24 09:21 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +from dataplattform.query.engine import Athena
ubrukt import

2020-07-24 09:21 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/requirements.txt
> +file:../../../../packages/query
ubrukt avhengighet

2020-07-24 09:26 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/test_cv_partner_process_lambda.py
> +from cv_partner_process_lambda import handler, url
Ingen tester

2020-07-24 09:28 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/serverless.yml
> +service: test-lambda
Gi tjenesten et navn, følg samme format som i de andre tjenestene

2020-07-24 09:28 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/serverless.yml
> +    dataFolder: cvpartner/repos
`repos` gir vel ikke så mye mening i denne sammenhengen

2020-07-24 09:32 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +    return {'cv_partner': df_new}
mtp datastrukturen i json filen så ser jeg ikke hvordan dette skal fungere. Jeg tror også at kun en tabell er en alt for simpel datastruktur for CVpartner data.

2020-07-24 09:35 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +            'image': person['image']['thumb']
Testet bilde-URLene. De er ikke mulig å kalle uautorisert. Så her må vi gjøre noe mer smart. f.eks lagre dem i json base64 encoded

2020-07-24 09:37 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +    return {'cv_partner': df_new}
Mangler filter som sjekker at vi ikke legger til data som alt finnes i systemet, ingest-funksjonen din poller jo inn alt, helt ukritisk hver 7-dag (serverless schedule)

2020-07-24 09:41 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +    res = requests.get(url + '/users?offset=0', headers={'Authorization': f'Bearer {api_token}'})
Jeg tror ikke du får alt med ett kall (sånn som dokumentasjonen sier). Du må nok page igjennom med offset-parameteren for å få alt. Sjekket noen av de største json-filene som lå i S3 og fant ikke meg selv, så det er definitivt noe som mangler

2020-07-24 09:44 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +    return Data(metadata=Metadata(timestamp=time), data=get_list_of_users())
CVpartner inneholder CVer for konslenter fra nesten hele knowit-konsernet. Vi er for nå kun intressert i å hente ut konsulenter fra Objectnet og objectnets datterselskap.

2020-07-24 09:47 UTC, jkrmc12 commented
Du må legge til en github actions workflow for denne tjenesten. se https://github.com/knowit/Dataplattform/tree/master/.github/workflows for ref

2020-07-27 08:15 UTC, HeleneSemmerud commented
@long11 : Jeg er enig med med forslagene til @jkrmc12 så langt. Ser gjennom hele reviewet når du har innført disse.

2020-08-11 07:42 UTC, long11 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +    return Data(metadata=Metadata(timestamp=time), data=get_list_of_users())
Hvilke selskaper er objectnets datterselskaper?

2020-09-07 09:19 UTC, jkrmc12 requested changes

2020-09-07 09:19 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +        return col1_series_out, col2_series_out
`col2_series_out` ser ikke ut til å være i bruk noe sted. `normalize_columns` brukes bare i `create_df` og der blir den bare kastet

2020-09-07 09:19 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +@handler.process(partitions={})
Jeg tenker vi hekter på en ny opsjon her for å gjøre en overwrite fremfor append når det kommer ny data

2020-09-07 09:19 UTC, jkrmc12 commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +        tmp_df = create_from_topic('user_id', user_ids, cat_dict)
```suggestion
        df = create_from_topic('user_id', user_ids, cat_dict)[cols].copy()
```
Så trenger vi ikke så mange `tmp*` variabler

2020-09-07 10:43 UTC, HeleneSemmerud commented on services/ingestion/poller/cvPartner/cv_partner_process_lambda.py
> +@handler.process(partitions={})
Har laget egen issue https://github.com/knowit/Dataplattform-issues/issues/238

2020-09-07 10:46 UTC, long11 commented on services/ingestion/poller/cvPartner/cv_partner_ingest_lambda.py
> +            user['cv'] = get_cv(user['user_id'], user['default_cv_id'])
Ja, det går fint nå. Vi bruker en annen url nå :)

2020-09-07 12:58 UTC, jkrmc12 approved these changes

2020-09-07 14:58 UTC, merged