Feature/create datacatalogue api
knowit/Dataplattform pull request #98
Opened 2020-08-21 09:05 UTC by HeleneSemmerud

2020-08-24 18:10 UTC, HeleneSemmerud commented on services/infrastructure/cognito/serverless.yml
> +                    - "*"
det er jeg enig i, men jeg fikk det ikke til. Kan du hjelpe meg?

2020-09-01 13:05 UTC, jkrmc12 requested changes

2020-09-01 13:05 UTC, jkrmc12 commented on services/dataCatalogueApi/app.py
> +@api.route('/database/<string:database_name>/table/<string:table_name>')
Jeg synes vi skal ha en route hit som er uavgengig av database også
rett på -> `/table/<string:table_name>`

2020-09-01 13:05 UTC, jkrmc12 commented on services/dataCatalogueApi/app.py
> +@api.route('/database/<string:database_name>/', strict_slashes=False)
Jeg ser ingen route for å liste databaser, eller en modell for det

2020-09-01 13:28 UTC, HeleneSemmerud commented on packages/testing/dataplattform/testing/plugin.py
> +    if "AWS_DEFAULT_REGION" not in environ:
jeg har ikke gjort det

2020-09-04 08:33 UTC, jkrmc12 approved these changes

2020-09-04 10:30 UTC, merged